dist: trusty
sudo: required
language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install build-essential
  - sudo apt-get -y install libncurses-dev cmake clang g++ wget git libssl-dev
  - sudo apt-get -y install bc nano patch mosquitto
  - sudo apt-get -y install libelf-dev sparse flawfinder
  - sudo apt-get -y install libedit-dev

script:
  - cd ./v0.3.1 && make prepare && make config_travis && make compile && make install && rm -rf build

notifications:
  slack: camflow:T3Umf9cAIwKnaxFEkjeZV7RM
