dist: trusty
sudo: required
language: c

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    packages:
    # install toolchains
    - gcc-7
    - g++-7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install build-essential
  - sudo apt-get -y install libncurses-dev cmake clang g++ wget git libssl-dev
  - sudo apt-get -y install bc nano patch mosquitto
  - sudo apt-get -y install libelf-dev sparse flawfinder
  - sudo apt-get -y install libedit-dev

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-7 /usr/bin/g++
  - gcc --version
  - g++ --version
  - cd ./v0.6.5 && make prepare && make config_travis && make compile && make install

notifications:
  slack: camflow:T3Umf9cAIwKnaxFEkjeZV7RM
