version: 2.1
orbs:
  cloudsmith: cloudsmith/cloudsmith@1.0.1
jobs:
  checkout:
    docker:
      - image: kernelci/build-gcc-8_x86:latest
    working_directory: ~/build
    steps:
      - checkout
      - restore_cache:
         keys:
           - build-{{ checksum ".circleci/config.yml" }}
      - run:
          name: 'Prepare build environment...'
          command: |
            if [ -d "~/build/linux-stable" ]; then
              echo 'Build environment was cached.'
            else
              echo 'Build environment was not cached.'
              apt-get update -qq --allow-releaseinfo-change
              apt-get install patch
              apt-get install --reinstall make
              make prepare
            fi
      - save_cache:
          key: build-{{ checksum ".circleci/config.yml" }}
          paths:
            - build
      - persist_to_workspace:
          root: ~/build
          paths:
            - linux-stable
  fedora_security:
    docker:
      - image: kernelci/build-gcc-8_x86:latest
    working_directory: ~/build
    steps:
      - checkout
      - attach_workspace:
          at: ~/build
      - run: 'apt-get update -qq --allow-releaseinfo-change'
      - run: 'apt-get install -y sudo rpm cpio'
      - run: 'apt-get install -y build-essential rsync libtool libncurses5-dev libncursesw5-dev bc pkg-config zsh libelf-dev bison flex'
      - run: 'make config_circle_fedora'
      - run: 'make compile_security'
  fedora_x86:
    docker:
      - image: fedora:35
    resource_class: xlarge
    working_directory: ~/build
    steps:
      - checkout
      - run: 'sudo dnf install -y make wget rsync'
      - run: 'sudo dnf install -y fedpkg fedora-packager rpmdevtools ncurses-devel pesign grubby'
      - run:
          command: 'make fedora'
          no_output_timeout: '60m'
      - persist_to_workspace:
          root: ~/build
          paths:
            - output
  publish:
    executor: cloudsmith/default
    working_directory: ~/build
    steps:
      - checkout
      - attach_workspace:
          at: ~/build
      - cloudsmith/ensure-api-key
      - cloudsmith/install-cli
      - run: 'cd ./output && ls'
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: camflow/camflow
          package-path: output/kernel-5*.x86_64.rpm
          package-format: rpm
          package-distribution: fedora/36
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: camflow/camflow
          package-path: output/kernel-5*.src.rpm
          package-format: rpm
          package-distribution: fedora/36
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: camflow/camflow
          package-path: output/kernel-core-5*.x86_64.rpm
          package-format: rpm
          package-distribution: fedora/36
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: camflow/camflow
          package-path: output/kernel-cross-headers-5*.x86_64.rpm
          package-format: rpm
          package-distribution: fedora/36
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: camflow/camflow
          package-path: output/kernel-debug-5*.x86_64.rpm
          package-format: rpm
          package-distribution: fedora/36
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: camflow/camflow
          package-path: output/kernel-debug-core-5*.x86_64.rpm
          package-format: rpm
          package-distribution: fedora/36
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: camflow/camflow
          package-path: output/kernel-debug-debuginfo-5*.x86_64.rpm
          package-format: rpm
          package-distribution: fedora/36
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: camflow/camflow
          package-path: output/kernel-debug-devel-5*.x86_64.rpm
          package-format: rpm
          package-distribution: fedora/36
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: camflow/camflow
          package-path: output/kernel-debug-modules-5*.x86_64.rpm
          package-format: rpm
          package-distribution: fedora/36
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: camflow/camflow
          package-path: output/kernel-debug-modules-extra-5*.x86_64.rpm
          package-format: rpm
          package-distribution: fedora/36
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: camflow/camflow
          package-path: output/kernel-debug-modules-internal-5*.x86_64.rpm
          package-format: rpm
          package-distribution: fedora/36
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: camflow/camflow
          package-path: output/kernel-debuginfo-5*.x86_64.rpm
          package-format: rpm
          package-distribution: fedora/36
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: camflow/camflow
          package-path: output/kernel-debuginfo-common-x86_64-5*.x86_64.rpm
          package-format: rpm
          package-distribution: fedora/36
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: camflow/camflow
          package-path: output/kernel-devel-5*.x86_64.rpm
          package-format: rpm
          package-distribution: fedora/36
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: camflow/camflow
          package-path: output/kernel-headers-5*.x86_64.rpm
          package-format: rpm
          package-distribution: fedora/36
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: camflow/camflow
          package-path: output/kernel-modules-5*.x86_64.rpm
          package-format: rpm
          package-distribution: fedora/36
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: camflow/camflow
          package-path: output/kernel-modules-extra-5*.x86_64.rpm
          package-format: rpm
          package-distribution: fedora/36
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: camflow/camflow
          package-path: output/kernel-modules-internal-5*.x86_64.rpm
          package-format: rpm
          package-distribution: fedora/36
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout
      - fedora_security:
          requires:
            - checkout
      - fedora_x86:
          requires:
            - fedora_security
      - publish:
          filters:
              branches:
                  only:
                      - master
          requires:
            - fedora_x86
