version: 2
jobs:
  build:
    working_directory: ~/
    docker:
      - image: buildpack-deps:zesty
    steps:
      - run:
          name: ruby
          command: 'apt -y install ruby'
      - run:
          name: package_cloud
          command: 'gem install package_cloud'
      - run:
          name: build-essential
          command: 'apt -y install build-essential'
      - run:
          name: dependencies
          command: 'apt -y install rpm libncurses-dev cmake clang g++ wget git libssl-dev bc patch libedit-dev libelf-dev'
      - checkout
      - run:
          name: prepare
          command: 'cd ./v0.3.1 && make prepare'
      - run:
          name: config
          command: 'cd ./v0.3.1 && make config_circle'
      - run:
          name: rpm
          command: 'cd ./v0.3.1 && make rpm'
      - deploy:
          name: publish
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cd ./v0.3.1 && make publish
            fi
