version: 2.1
jobs:
  checkout:
    docker:
      - image: moul/kernel-builder:latest
    working_directory: ~/circulate
    steps:
      - checkout
      - restore_cache:
         keys:
           - build-{{ checksum ".circleci/config.yml" }}
      - run:
          name: 'Prepare build environment...'
          command: |
            if [ -d "build/linux-stable" ]; then
              echo 'Build environment was cached.'
            else
              echo 'Build environment was not cached.'
              apt-get update -qq
              apt-get install -y sudo rpm cpio
              apt-get install -y uncrustify rsync build-essential ruby python autoconf automake libtool libncurses5-dev libncursesw5-dev bc libssl-dev pkg-config zsh libelf-dev bison flex sqlite3 libsqlite3-dev
              apt-get install --reinstall make
              cd ./v0.6.1
              make prepare
              ls
              cd ..
              ls
            fi
      - save_cache:
          key: build-{{ checksum ".circleci/config.yml" }}
          paths:
            - build
      - persist_to_workspace:
          root: ~/circulate
          paths:
            - .
  fedora:
    docker:
      - image: moul/kernel-builder:latest
    working_directory: ~/circulate
    steps:
      - checkout
      - attach_workspace:
          at: ~/circulate
      - run: 'apt-get update -qq'
      - run: 'apt-get install -y sudo rpm cpio'
      - run: 'apt-get install -y uncrustify rsync build-essential ruby python autoconf automake libtool libncurses5-dev libncursesw5-dev bc libssl-dev pkg-config zsh libelf-dev bison flex sqlite3 libsqlite3-dev'
      - run: 'apt-get install --reinstall make'
      - run: 'cd ./v0.6.1 && make config_circle_fedora'
      - run:
          command: 'cd ./v0.6.1 && make rpm'
          no_output_timeout: '30m'
      - run: 'cd ./v0.6.1 && make move_rpm'
      - persist_to_workspace:
          root: ~/circulate
          paths:
            - .
  ubuntu:
    docker:
      - image: moul/kernel-builder:latest
    working_directory: ~/circulate
    steps:
      - checkout
      - attach_workspace:
          at: ~/circulate
      - run: 'apt-get update -qq'
      - run: 'apt-get install -y sudo rpm cpio kmod'
      - run: 'apt-get install -y uncrustify rsync build-essential ruby python autoconf automake libtool libncurses5-dev libncursesw5-dev bc libssl-dev pkg-config zsh libelf-dev bison flex sqlite3 libsqlite3-dev'
      - run: 'apt-get install --reinstall make'
      - run: 'cd ./v0.6.1 && make config_circle_ubuntu'
      - run:
          command: 'cd ./v0.6.1 && make deb'
          no_output_timeout: '30m'
      - run: 'cd ./v0.6.1 && make move_deb'
      - persist_to_workspace:
          root: ~/circulate
          paths:
            - .
  publish:
    docker:
      - image: moul/kernel-builder:latest
    working_directory: ~/circulate
    steps:
      - checkout
      - attach_workspace:
          at: ~/circulate
      - run: 'apt-get update -qq'
      - run: 'apt-get install -y sudo rpm cpio'
      - run: 'apt-get install -y uncrustify rsync build-essential ruby python autoconf automake libtool libncurses5-dev libncursesw5-dev bc libssl-dev pkg-config zsh libelf-dev bison flex sqlite3 libsqlite3-dev'
      - run: 'apt-get install --reinstall make'
      - run: 'gem install rake'
      - run: 'gem install package_cloud'
      - deploy:
          name: publish
          command:
              cd ./v0.6.1 && make publish
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout
      - fedora:
          requires:
            - checkout
      - ubuntu:
          requires:
            - checkout
      - publish:
          filters:
            branches:
              only:
                - master
          requires:
            - fedora
            - ubuntu
