version: 2.1
jobs:
  checkout:
    docker:
      - image: kernelci/build-gcc-8_x86:latest
    working_directory: ~/circulate
    steps:
      - checkout
      - restore_cache:
         keys:
           - build-{{ checksum ".circleci/config.yml" }}
      - run:
          name: 'Prepare build environment...'
          command: |
            if [ -d "build/linux-stable" ]; then
              echo 'Build environment was cached.'
            else
              echo 'Build environment was not cached.'
              apt-get update -qq --allow-releaseinfo-change
              apt-get install --reinstall make
              make prepare
            fi
      - save_cache:
          key: build-{{ checksum ".circleci/config.yml" }}
          paths:
            - build
      - persist_to_workspace:
          root: ~/circulate
          paths:
            - .
  fedora_security:
    docker:
      - image: kernelci/build-gcc-8_x86:latest
    working_directory: ~/circulate
    steps:
      - checkout
      - attach_workspace:
          at: ~/circulate
      - run: 'apt-get update -qq --allow-releaseinfo-change'
      - run: 'apt-get install -y sudo rpm cpio'
      - run: 'apt-get install -y build-essential rsync libtool libncurses5-dev libncursesw5-dev bc pkg-config zsh libelf-dev bison flex'
      - run: 'make config_circle_fedora'
      - run: 'make compile_security'
  fedora:
    docker:
      - image: kernelci/build-gcc-8_x86:latest
    working_directory: ~/circulate
    steps:
      - checkout
      - attach_workspace:
          at: ~/circulate
      - run: 'apt-get update -qq --allow-releaseinfo-change'
      - run: 'apt-get install -y sudo rpm cpio'
      - run: 'apt-get install -y build-essential rsync libtool libncurses5-dev libncursesw5-dev bc pkg-config zsh libelf-dev bison flex'
      - run: 'make config_circle_fedora'
      - run:
          command: 'make rpm'
          no_output_timeout: '60m'
      - run: 'make move_rpm'
      - run: 'ls'
      - run: 'cd ~/circulate/  && ls'
      - run: 'cd ~/circulate/output && ls'
      - persist_to_workspace:
          root: ~/circulate
          paths:
            - ./output
  ubuntu_security:
    docker:
      - image: kernelci/build-gcc-8_x86:latest
    working_directory: ~/circulate
    steps:
      - checkout
      - attach_workspace:
          at: ~/circulate
      - run: 'apt-get update -qq --allow-releaseinfo-change'
      - run: 'apt-get install -y sudo rpm cpio'
      - run: 'apt-get install -y build-essential rsync libtool libncurses5-dev libncursesw5-dev bc pkg-config zsh libelf-dev bison flex'
      - run: 'make config_circle_ubuntu'
      - run: 'make compile_security'
  ubuntu:
    docker:
      - image: kernelci/build-gcc-8_x86:latest
    working_directory: ~/circulate
    steps:
      - checkout
      - attach_workspace:
          at: ~/circulate
      - run: 'apt-get update -qq --allow-releaseinfo-change'
      - run: 'apt-get install -y sudo rpm cpio'
      - run: 'apt-get install -y build-essential rsync libtool libncurses5-dev libncursesw5-dev bc pkg-config zsh libelf-dev bison flex'
      - run: 'make config_circle_ubuntu'
      - run:
          command: 'make deb'
          no_output_timeout: '90m'
      - run: 'make move_deb'
      - run: 'ls'
      - run: 'cd ~/circulate && ls'
      - run: 'cd ~/circulate/output && ls'
      - persist_to_workspace:
          root: ~/circulate
          paths:
            - ./output
  publish:
    docker:
      - image: kernelci/build-gcc-8_x86:latest
    working_directory: ~/circulate
    steps:
      - checkout
      - attach_workspace:
          at: ~/circulate
      - run: 'apt-get update -qq --allow-releaseinfo-change'
      - run: 'apt-get install --reinstall make'
      - run: 'apt-get install -y ruby ruby-dev'
      - run: 'apt-get install -y rename'
      - run: 'gem install rake'
      - run: 'gem install package_cloud'
      - deploy:
          name: publish
          command:
              make publish
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout
      - fedora_security:
          requires:
            - checkout
      - fedora:
          requires:
            - fedora_security
      - ubuntu_security:
          requires:
            - checkout
      - ubuntu:
          requires:
            - ubuntu_security
      - publish:
          filters:
            branches:
              only:
                - master
          requires:
            - fedora
            - ubuntu
