version: 2
jobs:
  build:
    docker:
      - image: moul/kernel-builder:latest
    working_directory: ~/circulate
    steps:
      - checkout
      - run:
          name: update
          command: 'apt-get update -qq'
      - run:
          name: install-add-apt-repository
          command: 'apt-get -y install software-properties-common python-software-properties'
      - run:
          name: toolchain-r
          command: 'add-apt-repository ppa:ubuntu-toolchain-r/test'
      - run:
          name: update2
          command: 'apt-get update'
      - run:
          name: build-essential
          command: 'apt-get -y install build-essential'
      - run:
          name: dependencies
          command: 'apt-get -y install rpm libncurses-dev cmake clang wget git libssl-dev bc patch libedit-dev libelf-dev'
      - run:
          name: gcc-4.9
          command: 'apt-get install -y gcc-4.9 g++-4.9'
      - run:
          name: link-gcc
          command: 'update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 100 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9'
      - run:
          name: gcc-version
          command: 'gcc --version'
      - run:
          name: g++-version
          command: 'g++ --version'
      - run:
          name: prepare
          command: 'cd ./v0.3.11 && make prepare'
      - run:
          name: config
          command: 'cd ./v0.3.11 && make config_circle'
      - run:
          name: rpm
          command: 'cd ./v0.3.11 && make rpm'
          no_output_timeout: 3600
      - run:
          name: move
          command: 'cd ./v0.3.11 && make move'
      - run:
          name: ruby
          command: 'apt-get -y install ruby2.3 ruby2.3-dev'
      - run:
          name: rake
          command: 'gem install rake'
      - run:
          name: package_cloud
          command: 'gem install package_cloud'
      - deploy:
          name: publish
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cd ./v0.3.11 && make publish
            fi
